language: node_js
node_js:
  - "6"
  - "10"
before_script:
  - yarn global add codecov
script:
  - yarn run lint
  - yarn run test
after_success:
  - codecov
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  yarn: true
  directories:
    - node_modules
