language: node_js
node_js:
  - "6"
script:
  - yarn run lint
  - yarn run test
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  yarn: true
  directories:
    - node_modules
